#line 2 "lex.yy.cc"

#line 4 "lex.yy.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

#define YY_FLEX_LEX_COMPAT
extern int yylineno;
int yylineno = 1;

extern char yytext[];

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	if ( yyleng >= YYLMAX ) \
		YY_FATAL_ERROR( "token too large, exceeds YYLMAX" ); \
	yy_flex_strncpy( yytext, (yytext_ptr), yyleng + 1 ); \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 22
#define YY_END_OF_BUFFER 23
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[165] =
    {   0,
        0,    0,   23,   21,    2,    1,   21,   21,   16,   21,
       21,   15,   13,   21,   21,   21,   21,   21,   21,   14,
       21,    0,   21,   21,    0,   19,    0,   21,   21,   21,
       21,    0,   18,    0,   21,   12,   11,   10,    0,   20,
       20,   21,    7,   21,   21,   21,   21,   21,   19,   19,
        0,   20,   20,   19,   21,   21,    0,   18,    0,   21,
       21,    0,    0,   21,   17,   18,   18,    0,   20,   20,
       18,   21,    9,   20,   20,   20,   21,   21,   21,   21,
       21,   19,   20,   19,   20,   20,   18,   18,    0,   20,
       20,   18,   21,   17,    0,   17,   20,   20,   21,   17,

       18,   20,   18,   20,   20,   20,   20,   20,   20,    3,
       21,   21,   21,   21,   20,   20,   19,   20,   19,   20,
       18,   20,   18,   20,   20,   17,   20,   20,   17,   20,
       20,   20,   18,   20,   18,   20,   21,   21,   21,   21,
       20,   20,   18,   20,   18,   20,   20,   20,   20,   17,
       20,   17,   21,    5,   21,   21,   21,    0,   21,    4,
        8,    6,    8,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    6,    1,    7,    8,    9,
       10,    1,    1,    1,    1,    1,    1,    1,    1,   11,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   12,
        1,   13,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   14,    1,    1,    1,    1,    1,    1,   15,   16,

       17,    1,    1,    1,   18,    1,    1,    1,    1,   19,
       20,   21,    1,   22,   23,   24,   25,   26,    1,   27,
        1,    1,   28,   29,   30,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[31] =
    {   0,
        1,    2,    3,    4,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    1,    1,    1,    1,    1,    6,    1,
        1,    1,    1,    6,    1,    1,    1,    1,    5,    1
    } ;

static const flex_int16_t yy_base[206] =
    {   0,
        0,    0,  138,   18, 1486, 1486,   46,   67,   20,   95,
       23,   25,   28,  123,   42,   50,   56,  140,   53,  121,
       32,  117,  168,  196,  115,   60,   86,  224,  252,  280,
      309,  108,    0,   90,  337,   98,   93,   79,    0,   99,
      103,   41,  101,  105,  115,  108,  126,  135, 1486,   73,
      156,  365,  160,  164,  393,  421,   58,    0,  175,  449,
      477,   35,  154,  506,  177,   54,  191,  199,  535,  180,
      563,  201,   43,  210,  591,  217,  220,  203,  222,  228,
      246,  244,  265,   81,  619,  647,   43,  270,  266,  670,
      285,  698,  275, 1486,  725,   26,  754,  289,  783,  294,

      298,  312,  302,  812,  840,  322,  328,  863,  330,  314,
      333,  335,  345,  358,  349,  378,  374,  891,  387,  919,
      397,  400,  402,  942,  970,  406,  410,  993,  108, 1022,
        0,  424,    0, 1051,  434, 1079,  404,  415,  432,  441,
        0,  461,    0, 1102,  474, 1130, 1153,  483, 1182,  478,
     1211,  480,  482,  443,  485,  502,  491,    0,  515,  489,
        0,  513,    0, 1486, 1241, 1247, 1253, 1259, 1265, 1271,
     1277, 1283, 1289, 1295, 1301, 1307, 1313, 1319, 1324, 1330,
     1336, 1342, 1348, 1354, 1360, 1366, 1372, 1378, 1384, 1390,
     1396, 1401, 1407, 1413, 1419, 1425, 1431, 1437, 1443, 1449,

     1455, 1461, 1467, 1473, 1479
    } ;

static const flex_int16_t yy_def[206] =
    {   0,
      164,    1,  164,  165,  164,  164,  166,  165,  165,  167,
      165,  165,  168,  169,  165,  165,  165,  165,  165,  168,
      165,  168,  169,  166,  170,  165,  171,  172,  173,  174,
      167,  175,   31,  176,  177,  168,  168,  168,  178,  179,
      164,  179,  165,  165,  165,  165,  165,  165,  164,  168,
      180,  181,  170,  179,  181,  173,  182,   56,  183,  184,
      174,  185,  186,  187,  165,  175,  176,  188,  189,  175,
      189,   71,  168,  164,  190,  191,  165,  165,  165,  165,
      165,  164,  170,  179,  192,  193,  182,  183,  194,  195,
      182,  195,   92,  164,  196,  168,  197,  185,  197,  179,

      175,  175,   71,  198,  199,  179,  164,  190,  191,  165,
      165,  165,  165,  165,   55,  170,  179,  192,  164,  193,
      182,  182,   92,  200,  201,  164,  185,  202,  179,  203,
       71,  175,   71,  198,  175,  199,  165,  165,  165,  165,
       92,  182,   92,  200,  182,  201,  197,  185,  202,  179,
      203,  164,  165,  165,  165,  165,  165,  204,  165,  165,
      205,  165,  205,    0,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,

      164,  164,  164,  164,  164
    } ;

static const flex_int16_t yy_nxt[1517] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,    4,    4,
       11,   12,   13,   14,   15,    4,   16,    4,    4,    4,
       17,    4,   18,    4,   19,    4,    4,    4,   20,    4,
       22,   23,   22,   23,   37,   36,   23,   22,   23,   39,
       38,   39,  164,  164,   22,   23,   22,   25,   22,   25,
       26,   22,   87,   22,   22,   23,   39,   43,   27,   28,
       22,   66,   22,   23,   94,   22,   23,   87,   22,   23,
       22,   48,   22,   23,   27,   29,   44,   45,   22,   22,
       23,   22,  164,  164,   22,   73,   39,   25,   22,   25,
       50,   32,   39,   32,   30,   22,   32,   67,   32,   51,

       74,   74,   33,   68,   74,   74,   39,   34,   35,  164,
      164,   39,   75,   22,   23,   66,   76,   22,   23,   49,
       22,   23,   77,   34,   41,   41,   41,   22,   23,   22,
       39,   79,   78,   22,   39,   41,   22,  164,   22,   23,
      164,   42,  164,   22,  164,  164,   42,   22,   23,  164,
       80,   41,   22,   23,   22,   62,   46,   81,   41,   47,
       82,   83,   74,   22,   49,   74,   74,   95,   22,   41,
       41,   41,  164,   86,   25,  164,   57,   75,   57,   25,
       41,  102,   74,   96,   88,  164,   42,   66,   89,   22,
       23,   42,   32,  105,   32,  164,   41,   25,   67,   25,

       26,   41,   32,  164,   68,   22,  101,  164,   27,   28,
      164,   74,   74,  164,   72,   22,   23,   32,  107,  107,
      164,  111,   32,   76,   27,   53,   41,   53,   54,  164,
      109,   22,   22,   23,   22,   23,   53,  164,  112,  164,
       22,   23,   55,  110,  164,   74,   74,   55,   22,  113,
       22,  164,   53,   57,  164,   57,   22,   76,   22,   23,
      164,   58,  114,  164,   59,   60,   83,   74,   41,   49,
      164,   57,  164,   57,   22,  121,   57,  164,   86,   88,
       59,   62,  164,   89,   57,  164,  122,   74,   93,   57,
      127,   74,   63,   64,   87,   74,   74,  164,  125,  102,

       74,  164,  130,   32,  164,   66,  164,   75,   63,   65,
       32,  105,   32,  102,   74,   72,   33,  164,   94,   66,
      164,   34,   35,   74,   74,  105,   22,   23,  164,   74,
       74,  107,  107,  164,  164,   75,  164,   34,   70,   41,
       70,   76,   22,  109,   71,   22,   23,   22,   23,   70,
       83,   74,  164,  138,  164,   72,  137,   22,   23,  139,
       72,   22,   85,   22,  164,   70,   83,   74,   25,   84,
       22,   23,  164,   22,  164,   74,   74,   25,   85,   83,
       74,  140,   49,  164,  164,  164,   22,   75,   74,   74,
      164,   86,  164,   25,   25,  164,   25,   84,  122,   74,

       76,  122,   74,   57,  164,   25,   87,   74,   74,   87,
      125,  127,   74,  125,  164,   93,   22,   23,  164,   76,
      153,   25,   57,  130,   57,  102,   74,   22,   23,  164,
       58,   66,   22,   59,   60,  102,   74,  105,  164,   94,
      154,   66,  164,   22,   22,   23,  164,  105,  155,   59,
       91,   41,   91,   22,   23,   22,   23,  156,   92,  164,
       22,   91,  122,   74,  164,  164,  164,   93,  164,   22,
       87,   22,   93,  164,  125,  122,   74,   91,   62,   74,
       74,   74,   74,   87,  127,   74,  164,  125,  158,   63,
       64,   75,  164,   76,   22,   23,  130,   22,   23,  164,

      157,   22,   23,   22,   23,   63,   65,   98,   41,   41,
       22,  164,   94,   22,   22,   23,  160,   22,   98,   22,
      159,  164,  164,  164,   99,   22,   23,   22,   23,   99,
       22,  164,  164,  164,   98,  100,  102,   74,   32,  164,
      162,   22,  103,   22,  164,  164,  164,   32,  104,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,   32,  102,   74,   32,  164,  164,  164,
      103,  164,  164,  164,  164,   32,  104,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,   32,  107,  107,   74,  164,  164,  164,  164,  164,

      164,  164,  164,   74,  108,  164,  164,  164,  164,   42,
      164,  164,  164,  164,   42,  164,  164,  164,  164,   74,
      116,  107,   83,  117,  164,  164,  164,  164,  164,  164,
      164,   83,  118,  164,  164,  164,  164,   55,  164,  164,
      164,  164,   55,  164,  164,  164,  164,   83,  116,  107,
      164,  119,  164,  164,  164,  164,  164,  164,  164,  164,
      120,  164,  164,  164,  164,   25,  164,  164,  164,  164,
       25,  122,   74,   57,  164,  164,  164,  164,  164,  123,
      164,  164,   57,  124,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,   57,  122,

       74,   57,  164,  164,  164,  164,  164,  123,  164,  164,
       57,  124,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,   57,   41,   41,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,   62,  164,  164,  164,  164,   62,  164,
      164,  164,  164,  164,  126,  127,   74,  164,  164,  164,
      164,  164,  164,  164,  164,  164,   62,  128,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,   62,  129,   62,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,   62,  164,  164,  164,  164,

      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,   62,  129,  132,  107,  102,  164,  164,  164,  133,
      164,  164,  164,  164,  102,  134,  164,  164,  164,  164,
       72,  164,  164,  164,  164,   72,  164,  164,  164,  164,
      102,  132,  107,  164,  164,  164,  164,  135,  164,  164,
      164,  164,  164,  136,  164,  164,  164,  164,   32,  164,
      164,  164,  164,   32,  107,  107,   74,  164,  164,  164,
      164,  164,  164,  164,  164,   74,  108,  164,  164,  164,
      164,   42,  164,  164,  164,  164,   42,  164,  164,  164,
      164,   74,  116,  107,   83,  117,  164,  164,  164,  164,

      164,  164,  164,   83,  118,  164,  164,  164,  164,   55,
      164,  164,  164,  164,   55,  164,  164,  164,  164,   83,
      116,  107,  164,  119,  164,  164,  164,  164,  164,  164,
      164,  164,  120,  164,  164,  164,  164,   25,  164,  164,
      164,  164,   25,  142,  107,  122,  164,  164,  164,  164,
      164,  143,  164,  164,  122,  144,  164,  164,  164,  164,
       93,  164,  164,  164,  164,   93,  164,  164,  164,  164,
      122,  142,  107,  164,  164,  164,  164,  164,  164,  145,
      164,  164,  164,  146,  164,  164,  164,  164,   57,  164,
      164,  164,  164,   57,  148,  107,   74,  164,  164,  164,

      164,  164,  164,  164,  164,  127,  149,  164,  164,  164,
      164,   99,  164,  164,  164,  164,   99,  164,  164,  164,
      164,  127,  150,  148,  107,   74,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  151,  164,  164,  164,  164,
       62,  164,  164,  164,  164,   62,  164,  164,  164,  164,
      164,  152,  132,  107,  102,  164,  164,  164,  133,  164,
      164,  164,  164,  102,  134,  164,  164,  164,  164,   72,
      164,  164,  164,  164,   72,  164,  164,  164,  164,  102,
      132,  107,  164,  164,  164,  164,  135,  164,  164,  164,
      164,  164,  136,  164,  164,  164,  164,   32,  164,  164,

      164,  164,   32,  142,  107,  122,  164,  164,  164,  164,
      164,  143,  164,  164,  122,  144,  164,  164,  164,  164,
       93,  164,  164,  164,  164,   93,  164,  164,  164,  164,
      122,  142,  107,  164,  164,  164,  164,  164,  164,  145,
      164,  164,  164,  146,  164,  164,  164,  164,   57,  164,
      164,  164,  164,   57,  127,   74,  164,  164,  164,  164,
      164,  164,  164,  164,  164,   62,  128,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,   62,  129,  148,  107,   74,  164,  164,  164,  164,
      164,  164,  164,  164,  127,  149,  164,  164,  164,  164,

       99,  164,  164,  164,  164,   99,  164,  164,  164,  164,
      127,  150,  148,  107,   74,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  151,  164,  164,  164,  164,   62,
      164,  164,  164,  164,   62,  164,  164,  164,  164,  164,
      152,   21,  164,  164,  164,   21,   21,   24,   24,  164,
       24,   24,   24,   31,   31,  164,   31,   31,   31,   22,
      164,  164,  164,   22,   22,   40,   40,   40,   40,   40,
       40,   25,   25,  164,   25,   25,   25,   27,   27,  164,
       27,   27,   27,   52,   52,   52,   52,   52,   52,   56,
       56,  164,   56,   56,   56,   61,   61,  164,  164,   61,

       61,   32,   32,  164,   32,   32,   32,   34,   34,  164,
       34,   34,   34,   69,   69,   69,   69,   69,   69,   41,
       41,   41,   41,   41,   42,   42,   42,  164,  164,   42,
       53,   53,   53,   53,   53,   53,   55,   55,   55,   55,
       55,   55,   57,   57,  164,   57,   57,   57,   59,   59,
      164,   59,   59,   59,   90,   90,   90,   90,   90,   90,
       62,   62,  164,  164,   62,   62,   63,   63,  164,  164,
       63,   63,   97,   97,   97,   97,   97,   97,   70,   70,
       70,   70,   70,   70,   72,   72,   72,   72,   72,   72,
      106,  106,  106,  106,  106,  106,   74,   74,   74,   74,

       74,  115,  115,  115,  115,  115,  115,   83,   83,   83,
       83,   83,   83,   91,   91,   91,   91,   91,   91,   93,
       93,   93,   93,   93,   93,   98,   98,   98,   98,   98,
       98,   99,   99,   99,  164,   99,   99,  131,  131,  131,
      131,  131,  131,  102,  102,  102,  102,  102,  102,  141,
      141,  141,  141,  141,  141,  122,  122,  122,  122,  122,
      122,  147,  147,  147,  147,  147,  147,  127,  127,  127,
      127,  127,  127,  161,  164,  164,  164,  161,  161,  163,
      164,  164,  164,  163,  163,    3,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,

      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164
    } ;

static const flex_int16_t yy_chk[1517] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        4,    4,    9,    9,   13,   11,   11,   12,   12,   96,
       13,   13,   42,   42,   21,   21,    4,    7,    9,    7,
        7,   11,   87,   12,   15,   15,   73,   15,    7,    7,
       21,   66,   16,   16,   62,   19,   19,   57,   17,   17,
       15,   19,   26,   26,    7,    8,   16,   17,   16,    8,
        8,   19,   84,   84,   17,   38,   50,   27,   26,   27,
       27,   34,   38,   34,    8,    8,   10,   34,   10,   27,

       40,   40,   10,   34,   41,   41,   37,   10,   10,  129,
      129,   36,   40,   43,   43,   32,   41,   44,   44,   25,
       46,   46,   44,   10,   14,   14,   14,   45,   45,   43,
       22,   46,   45,   44,   20,   14,   46,    3,   47,   47,
        0,   14,    0,   45,    0,    0,   14,   48,   48,    0,
       47,   14,   18,   18,   47,   63,   18,   48,   51,   18,
       51,   53,   53,   48,   53,   54,   54,   63,   18,   23,
       23,   23,    0,   53,   51,    0,   59,   54,   59,   51,
       23,   70,   70,   63,   59,    0,   23,   70,   59,   65,
       65,   23,   67,   70,   67,    0,   23,   24,   67,   24,

       24,   68,   72,   72,   67,   65,   68,    0,   24,   24,
        0,   74,   74,    0,   72,   78,   78,   68,   76,   76,
        0,   78,   68,   74,   24,   28,   28,   28,   28,    0,
       76,   78,   77,   77,   79,   79,   28,    0,   79,    0,
       80,   80,   28,   77,    0,   82,   82,   28,   77,   80,
       79,    0,   28,   29,    0,   29,   80,   82,   81,   81,
        0,   29,   81,    0,   29,   29,   83,   83,   89,   83,
        0,   88,    0,   88,   81,   89,   93,   93,   83,   88,
       29,   30,    0,   88,   89,    0,   91,   91,   93,   89,
       98,   98,   30,   30,   91,  100,  100,    0,   91,  101,

      101,    0,   98,  103,  103,  101,    0,  100,   30,   30,
       31,  101,   31,  102,  102,  103,   31,    0,   98,  102,
        0,   31,   31,  106,  106,  102,  110,  110,    0,  107,
      107,  109,  109,    0,    0,  106,    0,   31,   35,   35,
       35,  107,  110,  109,   35,  111,  111,  112,  112,   35,
      115,  115,    0,  112,    0,   35,  111,  113,  113,  113,
       35,  111,  115,  112,    0,   35,   52,   52,   52,   52,
      114,  114,    0,  113,    0,  117,  117,   52,   52,  116,
      116,  114,  116,    0,    0,    0,  114,  117,  119,  119,
        0,  116,    0,   52,   55,   55,   55,   55,  121,  121,

      119,  122,  122,  123,  123,   55,  121,  126,  126,  122,
      121,  127,  127,  122,    0,  123,  137,  137,    0,  126,
      137,   55,   56,  127,   56,  132,  132,  138,  138,    0,
       56,  132,  137,   56,   56,  135,  135,  132,    0,  127,
      138,  135,    0,  138,  139,  139,    0,  135,  139,   56,
       60,   60,   60,  140,  140,  154,  154,  140,   60,    0,
      139,   60,  142,  142,    0,    0,    0,   60,    0,  140,
      142,  154,   60,    0,  142,  145,  145,   60,   61,  150,
      150,  152,  152,  145,  148,  148,    0,  145,  155,   61,
       61,  150,    0,  152,  153,  153,  148,  155,  155,    0,

      153,  160,  160,  157,  157,   61,   61,   64,   64,   64,
      153,    0,  148,  155,  156,  156,  157,  160,   64,  157,
      156,    0,    0,    0,   64,  162,  162,  159,  159,   64,
      156,    0,    0,    0,   64,   64,   69,   69,   69,    0,
      159,  162,   69,  159,    0,    0,    0,   69,   69,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   69,   71,   71,   71,    0,    0,    0,
       71,    0,    0,    0,    0,   71,   71,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   71,   75,   75,   75,    0,    0,    0,    0,    0,

        0,    0,    0,   75,   75,    0,    0,    0,    0,   75,
        0,    0,    0,    0,   75,    0,    0,    0,    0,   75,
       85,   85,   85,   85,    0,    0,    0,    0,    0,    0,
        0,   85,   85,    0,    0,    0,    0,   85,    0,    0,
        0,    0,   85,    0,    0,    0,    0,   85,   86,   86,
        0,   86,    0,    0,    0,    0,    0,    0,    0,    0,
       86,    0,    0,    0,    0,   86,    0,    0,    0,    0,
       86,   90,   90,   90,    0,    0,    0,    0,    0,   90,
        0,    0,   90,   90,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   90,   92,

       92,   92,    0,    0,    0,    0,    0,   92,    0,    0,
       92,   92,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   92,   95,   95,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   95,    0,    0,    0,    0,   95,    0,
        0,    0,    0,    0,   95,   97,   97,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   97,   97,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   97,   97,   99,   99,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   99,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   99,   99,  104,  104,  104,    0,    0,    0,  104,
        0,    0,    0,    0,  104,  104,    0,    0,    0,    0,
      104,    0,    0,    0,    0,  104,    0,    0,    0,    0,
      104,  105,  105,    0,    0,    0,    0,  105,    0,    0,
        0,    0,    0,  105,    0,    0,    0,    0,  105,    0,
        0,    0,    0,  105,  108,  108,  108,    0,    0,    0,
        0,    0,    0,    0,    0,  108,  108,    0,    0,    0,
        0,  108,    0,    0,    0,    0,  108,    0,    0,    0,
        0,  108,  118,  118,  118,  118,    0,    0,    0,    0,

        0,    0,    0,  118,  118,    0,    0,    0,    0,  118,
        0,    0,    0,    0,  118,    0,    0,    0,    0,  118,
      120,  120,    0,  120,    0,    0,    0,    0,    0,    0,
        0,    0,  120,    0,    0,    0,    0,  120,    0,    0,
        0,    0,  120,  124,  124,  124,    0,    0,    0,    0,
        0,  124,    0,    0,  124,  124,    0,    0,    0,    0,
      124,    0,    0,    0,    0,  124,    0,    0,    0,    0,
      124,  125,  125,    0,    0,    0,    0,    0,    0,  125,
        0,    0,    0,  125,    0,    0,    0,    0,  125,    0,
        0,    0,    0,  125,  128,  128,  128,    0,    0,    0,

        0,    0,    0,    0,    0,  128,  128,    0,    0,    0,
        0,  128,    0,    0,    0,    0,  128,    0,    0,    0,
        0,  128,  128,  130,  130,  130,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  130,    0,    0,    0,    0,
      130,    0,    0,    0,    0,  130,    0,    0,    0,    0,
        0,  130,  134,  134,  134,    0,    0,    0,  134,    0,
        0,    0,    0,  134,  134,    0,    0,    0,    0,  134,
        0,    0,    0,    0,  134,    0,    0,    0,    0,  134,
      136,  136,    0,    0,    0,    0,  136,    0,    0,    0,
        0,    0,  136,    0,    0,    0,    0,  136,    0,    0,

        0,    0,  136,  144,  144,  144,    0,    0,    0,    0,
        0,  144,    0,    0,  144,  144,    0,    0,    0,    0,
      144,    0,    0,    0,    0,  144,    0,    0,    0,    0,
      144,  146,  146,    0,    0,    0,    0,    0,    0,  146,
        0,    0,    0,  146,    0,    0,    0,    0,  146,    0,
        0,    0,    0,  146,  147,  147,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  147,  147,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  147,  147,  149,  149,  149,    0,    0,    0,    0,
        0,    0,    0,    0,  149,  149,    0,    0,    0,    0,

      149,    0,    0,    0,    0,  149,    0,    0,    0,    0,
      149,  149,  151,  151,  151,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  151,    0,    0,    0,    0,  151,
        0,    0,    0,    0,  151,    0,    0,    0,    0,    0,
      151,  165,    0,    0,    0,  165,  165,  166,  166,    0,
      166,  166,  166,  167,  167,    0,  167,  167,  167,  168,
        0,    0,    0,  168,  168,  169,  169,  169,  169,  169,
      169,  170,  170,    0,  170,  170,  170,  171,  171,    0,
      171,  171,  171,  172,  172,  172,  172,  172,  172,  173,
      173,    0,  173,  173,  173,  174,  174,    0,    0,  174,

      174,  175,  175,    0,  175,  175,  175,  176,  176,    0,
      176,  176,  176,  177,  177,  177,  177,  177,  177,  178,
      178,  178,  178,  178,  179,  179,  179,    0,    0,  179,
      180,  180,  180,  180,  180,  180,  181,  181,  181,  181,
      181,  181,  182,  182,    0,  182,  182,  182,  183,  183,
        0,  183,  183,  183,  184,  184,  184,  184,  184,  184,
      185,  185,    0,    0,  185,  185,  186,  186,    0,    0,
      186,  186,  187,  187,  187,  187,  187,  187,  188,  188,
      188,  188,  188,  188,  189,  189,  189,  189,  189,  189,
      190,  190,  190,  190,  190,  190,  191,  191,  191,  191,

      191,  192,  192,  192,  192,  192,  192,  193,  193,  193,
      193,  193,  193,  194,  194,  194,  194,  194,  194,  195,
      195,  195,  195,  195,  195,  196,  196,  196,  196,  196,
      196,  197,  197,  197,    0,  197,  197,  198,  198,  198,
      198,  198,  198,  199,  199,  199,  199,  199,  199,  200,
      200,  200,  200,  200,  200,  201,  201,  201,  201,  201,
      201,  202,  202,  202,  202,  202,  202,  203,  203,  203,
      203,  203,  203,  204,    0,    0,    0,  204,  204,  205,
        0,    0,    0,  205,  205,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,

      164,  164,  164,  164,  164,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[23] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#ifndef YYLMAX
#define YYLMAX 8192
#endif

char yytext[YYLMAX];
char *yytext_ptr;
#line 1 "shell.l"
/*
 *
 * CS-252 
 * shell.l: lexical analyzer for shell
 * You have to extend it.
 *
 */
#line 11 "shell.l"
#include <sys/wait.h>
#include <unistd.h>
#include <cstring>
#include "y.tab.hh"
#include <string.h>
#include <algorithm>
static  void yyunput (int c,char *buf_ptr  );

void myunputc(int c) {
  unput(c);
}

#line 888 "lex.yy.cc"
#line 889 "lex.yy.cc"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 27 "shell.l"


#line 1109 "lex.yy.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 165 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1486 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 29 "shell.l"
{
  return NEWLINE;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 33 "shell.l"
{
  /* Discard spaces and tabs */
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 37 "shell.l"
{
    return EXIT;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "shell.l"
{
    return PRINTENV;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 45 "shell.l"
{
    return SETENV;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 49 "shell.l"
{
    return UNSETENV;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 53 "shell.l"
{
    return CD;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 57 "shell.l"
{
     std::string str = std::string(yytext);
     str = str.substr(7, str.size());
     FILE * sourceFile = fopen(str.c_str(), "r+");

    if (!sourceFile) {
        perror("fopen");
        BEGIN(INITIAL);
    } else {
        fputc('\n', sourceFile);
        yypush_buffer_state(yy_create_buffer(sourceFile, YY_BUF_SIZE));
        BEGIN(INITIAL);
        yyparse();
        yypop_buffer_state();
        fclose(sourceFile);
    }
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 75 "shell.l"
{
    return GREATGREATAMP;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 79 "shell.l"
{
    return GREATGREAT;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 83 "shell.l"
{
    return GREATAMP;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 87 "shell.l"
{
    return TWOGREAT;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 91 "shell.l"
{
  return GREAT;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 95 "shell.l"
{
    return PIPE;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 99 "shell.l"
{
    return LESS;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 103 "shell.l"
{
    return AMPERSAND;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 107 "shell.l"
{
    std::string str = std::string(yytext);
    str = str.substr(2, str.size() - 3);
    str = getenv(str.c_str());
    yylval.cpp_string = new std::string(str);
    return WORD;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 115 "shell.l"
{
    std::string str = std::string(yytext);
    if (str.at(0) == '$') {
        str = str.substr(2, str.size() - 3);
    } else {
        str = str.substr(1, str.size() - 2);
    }
    int pin[2];
    int pout[2];

    pipe(pin);
    pipe(pout);

    int defaultin = dup(0);
    int defaultout = dup(1);


    dup2(pin[0], 0);
    dup2(pout[1], 1);
    close(pin[0]);
    close(pout[1]);


    int pid = fork();

    write(pin[1], str.c_str(), str.size());
    write(pin[1], "\n", 1);
    write(pin[1], "exit\n", 5);
    close(pin[1]);

    if(pid == -1) {
      perror("fork\n");
      exit(1);
    }
    //CHILD
    if (pid == 0) {
    char * arg[2];
    arg[1] = NULL;
    arg[0] =(char *) "shell";


    execvp("/proc/self/exe", arg);
    perror("execvp(subshell)");
    _exit(1);
    } else { //END CHILD

    waitpid(pid, NULL, 0);

    dup2(defaultin, 0);
    dup2(defaultout, 1);
    close(defaultin);
    close(defaultout);


    char c;
    std::string a;
    while(read(pout[0], &c, 1)) {
        if (c == '\n') {
            c =' ';
        }
        a.push_back(c);
    }
    close(pout[0]);
    for ( int i = a.size() - 1; i >= 0; i--) {
        myunputc(a.at(i));
    }
}
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 184 "shell.l"
{
  std::string str = std::string(yytext);
  str = str.substr(1, str.size() - 2);
  yylval.cpp_string = new std::string(str);
  return WORD;
}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 191 "shell.l"
{
    std::string str = std::string(yytext);
    /*for(int i = 0; i < str.size(); i++) {
        if (str.at(i) == '\\') {
            str.erase(str.begin() + i);
        }
    } */
    yylval.cpp_string = new std::string(str);
    return WORD;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 202 "shell.l"
{
  /* Assume that file names have only alpha chars */
  std::string str = std::string(yytext);
  yylval.cpp_string = new std::string(str);
  return WORD;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 208 "shell.l"
ECHO;
	YY_BREAK
#line 1426 "lex.yy.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 165 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 165 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 164);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 208 "shell.l"
